runtime: python311
entrypoint: gunicorn -b :$PORT sorolab_backend.wsgi

env: standard
instance_class: F1

handlers:
# Serve static files
- url: /static
  static_dir: static

# Serve media files
- url: /media
  static_dir: media

# Default: send all other requests to Django
- url: /.*
  script: auto
